//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMKJ.FenLiu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShuntContext : DbContext
    {
        public ShuntContext()
            : base("name=ShuntContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TbAnswer> TbAnswer { get; set; }
        public DbSet<TbApplyMajor> TbApplyMajor { get; set; }
        public DbSet<TbClass> TbClass { get; set; }
        public DbSet<TbDesire> TbDesire { get; set; }
        public DbSet<TbDissertation> TbDissertation { get; set; }
        public DbSet<TbInterviewScore> TbInterviewScore { get; set; }
        public DbSet<TbLession> TbLession { get; set; }
        public DbSet<TbLessionScore> TbLessionScore { get; set; }
        public DbSet<TbMajor> TbMajor { get; set; }
        public DbSet<TbQuesScore> TbQuesScore { get; set; }
        public DbSet<TbQuestion> TbQuestion { get; set; }
        public DbSet<TbRecord> TbRecord { get; set; }
        public DbSet<TbShunt> TbShunt { get; set; }
        public DbSet<TbStudent> TbStudent { get; set; }
        public DbSet<TbStudentClass> TbStudentClass { get; set; }
        public DbSet<TbTaskRecord> TbTaskRecord { get; set; }
        public DbSet<TbTaskRecordDetail> TbTaskRecordDetail { get; set; }
        public DbSet<TbTopic> TbTopic { get; set; }
        public DbSet<TbTotalScore> TbTotalScore { get; set; }
        public DbSet<TbUsers> TbUsers { get; set; }
    }
}
