//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMKJ.FenLiu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbClass
    {
        public TbClass()
        {
            this.TbRecord = new HashSet<TbRecord>();
            this.TbRecord1 = new HashSet<TbRecord>();
        }
    
        public string ClassId { get; set; }
        public string MajorId { get; set; }
        public string ClassName { get; set; }
        public int ClassCount { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual TbMajor TbMajor { get; set; }
        public virtual ICollection<TbRecord> TbRecord { get; set; }
        public virtual ICollection<TbRecord> TbRecord1 { get; set; }
    }
}
