//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMKJ.FenLiu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbLession
    {
        public TbLession()
        {
            this.TbLessionScore = new HashSet<TbLessionScore>();
        }
    
        public string LessionId { get; set; }
        public string LessionName { get; set; }
        public int LessionType { get; set; }
        public string MajorId { get; set; }
        public int LessionTime { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<TbLessionScore> TbLessionScore { get; set; }
    }
}
