//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMKJ.FenLiu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbQuestion
    {
        public string QuestionId { get; set; }
        public string MajorId { get; set; }
        public string StudentId { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string UsersId { get; set; }
        public Nullable<System.DateTime> QuestionTime { get; set; }
        public Nullable<System.DateTime> AnswerTime { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> Delflag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual TbMajor TbMajor { get; set; }
        public virtual TbStudent TbStudent { get; set; }
        public virtual TbUsers TbUsers { get; set; }
    }
}
