//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMKJ.FenLiu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbTotalScore
    {
        public string TotalScoreId { get; set; }
        public string StudentId { get; set; }
        public Nullable<double> InterviewScore { get; set; }
        public Nullable<double> MajorScore { get; set; }
        public Nullable<double> QuestionnaireScore { get; set; }
        public Nullable<double> DissertationScore { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual TbStudent TbStudent { get; set; }
    }
}
