//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMKJ.FenLiu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUsers
    {
        public TbUsers()
        {
            this.TbQuestion = new HashSet<TbQuestion>();
        }
    
        public string UsersId { get; set; }
        public string UserCode { get; set; }
        public string UserPwd { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Gender { get; set; }
        public int SysRole { get; set; }
        public string MajorId { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<TbQuestion> TbQuestion { get; set; }
    }
}
